name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: OutlawAndy
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, lines, stars, isocalendar, habits
          config_timezone: America/Chicago
          # config_display: columns
          base_indepth: yes
          output_action: commit
          output_condition: data-changed
          retries: 5
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          repositories: 100
          repositories_affiliations: owner, collaborator, organization_member
          repositories_batch: 50
          repositories_forks: yes
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          commits_authoring: >
            Andrew Cohen,
            Andy Cohen,
            OutlawAndy,
            outlawandy@gmail.com,
            yourstruly@outlawandy.com,
            andy@outlawandy.com,
            andy@setpoint.io,
            andy@setpoint.dev,
            andy.cohen@rolemodelsoftware.com

          plugins_errors_fatal: yes
          plugin_achievements: no
          # plugin_achievements_display: compact
          plugin_discussions: no
          # plugin_discussions_categories_limit: 0
          plugin_followup: no
          # plugin_followup_sections: user
          # plugin_followup_indepth: yes
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_habits_charts_types: chartist
          plugin_habits_trim: yes
          plugin_habits_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: no
          # plugin_languages_indepth: yes
          # plugin_languages_analysis_timeout: 30
          # plugin_languages_categories: markup, programming
          # plugin_languages_limit: 8
          # plugin_languages_threshold: 0%
          # plugin_languages_other: yes
          # plugin_languages_ignored: coffeescript, html
          plugin_lines: yes
          plugin_notable: no
          # plugin_notable_from: all
          # plugin_notable_types: commit, pull_request, issue
          # plugin_notable_indepth: yes
          # plugin_notable_repositories: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 938501
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 4
          plugin_stars: yes
          plugin_stars_limit: 4
          # plugin_topics: yes
          # plugin_topics_mode: icons